######################################################################
# Automatically generated by qmake (2.01a) jeu. avr. 19 09:56:19 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . /usr/include/ImageMagick

# Magick++
LIBS += -lMagick++

# Input
HEADERS += photoTweak.h
FORMS += photoTweak.ui
SOURCES += main.cpp photoTweak.cpp
